### OShot SMS Client Properties

## Common Properties
# '1' 이 아닌 다른 값으로 바꾸면 처리중인건은 처리 후 안정적으로 프로세스를 종료 할수 있다.
# (Delay 시간때문에 다소 시간이 걸리수 있음)
COMMON.RUN=1

# 공통/발송/결과 데이타 날짜별 로그 파일 (%LOGFILE%_YYYYMMDD.log)
# (윈도우 환경이라도 파일경로에 '\' 대신 '/'를 사용한다.  
COMMON.ADD_MSG_LENGTH=20
COMMON.ADD_MMS_LENGTH=1920
COMMON.LOGFILE=/home/nprism/server/deploy/other/oshot/logs/Common/Common
SEND.LOGFILE=/home/nprism/server/deploy/other/oshot/logs/Send/Send
MMS_SEND.LOGFILE=/home/nprism/server/deploy/other/oshot/logs/MmsSend/MmsSend
REPORT.LOGFILE=/home/nprism/server/deploy/other/oshot/logs/Report/Report
MMS_REPORT.LOGFILE=/home/nprism/server/deploy/other/oshot/logs/MmsReport/MmsReport

## 서버 연결정보 - 올샷에 가입된 회원정보
CONNECT.USER=daims
CONNECT.PASSWORD=daims03

# 발송서버 - 실제발송포트(33300)
SEND.RUN=1
SEND.HOST=203.251.202.55
SEND.PORT=33300

# 결과서버 - 실제결과수신포트(33301)
REPORT.RUN=1
REPORT.HOST=203.251.202.55
REPORT.PORT=33301

# MMS 발송서버 - 실제발송포트(33002)
MMS.SEND.RUN=1
MMS_SEND.HOST=203.251.202.55
MMS_SEND.PORT=33002

# MMS 결과서버 - 실제결과수신포트(33003)                               
MMSREPORT.RUN=1                 
MMS_REPORT.HOST=203.251.202.55
MMS_REPORT.PORT=33003

## DB 연결정보 - 고객쪽의 Database 연결정보
DB.USER=nprism
DB.PASSWORD=nprism03


# ORACLE
DB.DRIVERS=oracle.jdbc.driver.OracleDriver
DB.URL=jdbc:oracle:thin:@167.1.21.25:1521:DAIMS

# MSSQL
#DB.DRIVERS=com.microsoft.sqlserver.jdbc.SQLServerDriver
#DB.URL=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=SMS

# MYSQL
#DB.DRIVERS=com.mysql.jdbc.Driver
#DB.URL=jdbc:mysql://127.0.0.1:3306/sms


# ALTIBASE
#DB.DRIVERS=Altibase.jdbc.driver.AltibaseDriver
#DB.URL=jdbc:Altibase://127.0.0.1:20300/SMS


## DB Query(모든 Query 는 한줄로 나열한다.)

# DB.QUERY.SELECT=발송 요청 대상을 가져온다.(기존 시스템의 칼럼명이 틀리다면 'AS' 구문을 사용하여 아래 칼럼명으로 사용해야 한다.
# DB.QUERY.RESULT=발송 요청후 재발송 되지 않게 표시한다.(칼럼명의 순서가 바뀌면 안된다.)
# DB.QUERY.REPORT=핸드폰으로 발송된 결과를 Update 한다.(칼럼명의 순서가 바뀌면 안된다.)

# ORACLE
DB.QUERY.SELECT=SELECT MsgID, Sender, Receiver, Msg, URL, TO_CHAR(ReserveDT,'YYYY-MM-DD HH24:MI:SS') AS ReserveDT, TO_CHAR(TimeOutDT,'YYYY-MM-DD HH24:MI:SS') AS TimeOutDT FROM OSHOT_SMS WHERE SendResult=0 AND ( ReserveDt IS NULL OR ReserveDT <= SYSDATE ) AND ROWNUM <= 300
DB.QUERY.RESULT=UPDATE  /*+ INDEX_ASC(AllShotSMS    PK_ALLSHOTSMS) */ OSHOT_SMS SET SendResult=1 WHERE MsgID=? AND SendResult=0
DB.QUERY.REPORT=UPDATE  /*+ INDEX_ASC(AllShotSMS    PK_ALLSHOTSMS) */ OSHOT_SMS SET SendDT=TO_DATE(?,'YYYY-MM-DD HH24:MI:SS'), SendResult=?, Telecom=? WHERE MsgID=? AND SendResult=1

# MSSQL
#SMS#
#DB.QUERY.SELECT=SELECT TOP 300 MsgID, Sender, Receiver, Msg, URL, CONVERT(VARCHAR(19),ReserveDT,120) AS ReserveDT, CONVERT(VARCHAR(19),TimeOutDT,120) AS TimeOutDT FROM AllShotSMS WITH(NOLOCK) WHERE SendResult=0 AND ( ReserveDt IS NULL OR ReserveDT <= getdate() )
#DB.QUERY.RESULT=UPDATE AllShotSMS WITH(ROWLOCK) SET SendResult=1 WHERE MsgID=? AND SendResult=0
#DB.QUERY.REPORT=UPDATE AllShotSMS WITH(ROWLOCK) SET SendDT=convert(datetime,?), SendResult=?, Telecom=? WHERE MsgID=? AND SendResult=1
#MMS#
#DB.QUERY.MMS.CHECK=select TOP 1 msggroupid from AllShotMMS WITH(NOLOCK) WHERE SendResult=0 AND ( ReserveDt IS NULL OR ReserveDT <= getdate() ) group by msggroupid
#DB.QUERY.MMS.SELECT=SELECT TOP 300 MsgID, Sender, Receiver, Msg, URL, CONVERT(VARCHAR(19),ReserveDT,120) AS ReserveDT, CONVERT(VARCHAR(19),TimeOutDT,120) AS TimeOutDT, FILE_PATH1, SUBJECT  FROM AllShotMMS WHERE SendResult=0 AND ( ReserveDt IS NULL OR ReserveDT <= getdate() ) AND MSGGROUPID=? 
#DB.QUERY.MMS.RESULT=UPDATE AllShotMMS WITH(ROWLOCK) SET SendResult=1 WHERE MsgID=? AND SendResult=0
#DB.QUERY.MMS.REPORT=UPDATE AllShotMMS WITH(ROWLOCK) SET SendDT=convert(datetime,?), SendResult=?, Telecom=? WHERE MsgID=? AND SendResult=1

# MYSQL
#SMS#
#DB.QUERY.SELECT=SELECT MsgID, Sender, Receiver, Msg, URL, DATE_FORMAT(ReserveDT,'%Y-%m-%d %H:%i:%s') AS ReserveDT, DATE_FORMAT(TimeOutDT,'%Y-%m-%d %H:%i:%s') AS TimeOutDT FROM AllShotSMS WHERE SendResult=0 AND ( ReserveDt IS NULL OR ReserveDT <= now() ) LIMIT 300
#DB.QUERY.RESULT=UPDATE AllShotSMS SET SendResult=1 WHERE MsgID=? AND SendResult=0
#DB.QUERY.REPORT=UPDATE AllShotSMS SET SendDT=?, SendResult=?, Telecom=? WHERE MsgID=? AND SendResult=1
#MMS#
#DB.QUERY.MMS.CHECK=select msggroupid from allshotmms where sendresult = 0 AND ( ReserveDt IS NULL OR ReserveDT <= now()) group by msggroupid LIMIT 1
#DB.QUERY.MMS.SELECT=SELECT MsgID, Sender, Receiver, Msg, DATE_FORMAT(ReserveDT,'%Y-%m-%d %H:%i:%s') AS ReserveDT, DATE_FORMAT(TimeOutDT,'%Y-%m-%d %H:%i:%s')AS TimeOutDT, FILE_PATH1, SUBJECT  FROM AllShotMMS WHERE SendResult=0 AND ( ReserveDt IS NULL OR ReserveDT <= now() ) AND MSGGROUPID=? LIMIT 300
#DB.QUERY.MMS.RESULT=UPDATE AllShotMMS SET SendResult=1 WHERE MsgID=? AND SendResult=0
#DB.QUERY.MMS.REPORT=UPDATE AllShotMMS SET SendDT=?, SendResult=?, Telecom=? WHERE MsgID=? AND SendResult=1

# ALTIBASE
#DB.QUERY.SELECT=SELECT MsgID, Sender, Receiver, Msg, URL, TO_CHAR(ReserveDT,'YYYY-MM-DD HH24:MI:SS') AS ReserveDT, TO_CHAR(TimeOutDT,'YYYY-MM-DD HH24:MI:SS') AS TimeOutDT FROM AllShotSMS WHERE SendResult=0 AND ( ReserveDt IS NULL OR ReserveDT <= SYSDATE ) LIMIT 300
#DB.QUERY.RESULT=UPDATE AllShotSMS SET SendResult=1 WHERE MsgID=? AND SendResult=0
#DB.QUERY.REPORT=UPDATE AllShotSMS SET SendDT=TO_DATE(?,'YYYY-MM-DD HH24:MI:SS'), SendResult=?, Telecom=? WHERE MsgID=? AND SendResult=1



## Table Create & Data Move

# 월별 로그 Table 쌓기 : 발송결과(Report) 받은건(한번에 최대100건)에 대해서 발송일 기준 월 단위로 옮긴다
# No Move(0)/Move(1)
DB.MOVE.RUN=0

# $TARGET_TABLE$ = 'DB.MOVE.TARGET_TABLE' + 'SendDt' of 'DB.MOVE.SELECT' Query
#SMS#
DB.MOVE.TARGET_TABLE=AllShotSMS_
# 아래의 주석을 풀면 SMS로그 테이블을 고정 값으로 사용가능
#DB.MOVE.TARGET_TABLE_LOG=ALLSHOTSMS_LOG
#MMS#
# 월별 로그 Table 쌓기 : 발송결과(Report) 받은건(한번에 최대100건)에 대해서 발송일 기준 월 단위로 옮긴다
# No Move(0)/Move(1)
DB.MMS.MOVE.RUN=0
DB.MMS.MOVE.TARGET_TABLE=AllShotMMS_
# 아래의 주석을 풀면 MMS로그 테이블을 고정 값으로 사용가능
#DB.MMS.MOVE.TARGET_TABLE_LOG=ALLSHOTMMS_LOG


# ORACLE
# Table 생성
#DB.MOVE.CHECK_TABLE=SELECT table_name FROM user_tables WHERE table_name = UPPER(?)
#DB.MOVE.CREATE_TABLE=CREATE TABLE $TARGET_TABLE$ AS SELECT * FROM AllShotSMS WHERE 1=2
#DB.MOVE.ALTER_TABLE#1=ALTER TABLE $TARGET_TABLE$ ADD CONSTRAINT PK_$TARGET_TABLE$ PRIMARY KEY(MsgID)

# 데이타 이동
#DB.MOVE.SELECT=SELECT DISTINCT TO_CHAR(SendDT,'YYYYMM') AS SendDT FROM AllShotSMS WHERE SendResult>1
#DB.MOVE.INSERT=INSERT INTO $TARGET_TABLE$ SELECT * FROM AllShotSMS WHERE SendResult>1 AND TO_CHAR(SendDT,'YYYYMM')=?
#DB.MOVE.DELETE=DELETE FROM AllShotSMS WHERE SendResult>1 AND TO_CHAR(SendDT,'YYYYMM')=?


# MSSQL
#SMS##########################################################
# Table 생성
DB.MOVE.CHECK_TABLE=SELECT Name FROM sysobjects WHERE Type='U' and Name = ?
DB.MOVE.CREATE_TABLE=SELECT * INTO $TARGET_TABLE$ FROM AllShotSMS WHERE 1=2
DB.MOVE.ALTER_TABLE#1=ALTER TABLE $TARGET_TABLE$ DROP COLUMN MsgID
DB.MOVE.ALTER_TABLE#2=ALTER TABLE $TARGET_TABLE$ ADD MsgID INT NOT NULL DEFAULT (0)
DB.MOVE.ALTER_TABLE#3=CREATE UNIQUE INDEX IDX_$TARGET_TABLE$_MsgID on $TARGET_TABLE$(MsgID)

# 데이타 이동
DB.MOVE.SELECT=SELECT DISTINCT CONVERT(VARCHAR(6),SendDT,112) AS SendDT FROM AllShotSMS WHERE SendResult>1
DB.MOVE.INSERT=INSERT INTO $TARGET_TABLE$(MsgID,Sender,Receiver,Msg,URL,ReserveDT,TimeoutDT,SendDT,SendResult,Telecom) SELECT MsgID,Sender,Receiver,Msg,URL,ReserveDT,TimeoutDT,SendDT,SendResult,Telecom FROM AllShotSMS WHERE SendResult>1 AND CONVERT(VARCHAR(6),SendDT,112)=?
DB.MOVE.DELETE=DELETE FROM AllShotSMS WHERE SendResult>1 AND CONVERT(VARCHAR(6),SendDT,112)=?

#MMS##########################################################
DB.MMS.MOVE.CHECK_TABLE=SELECT Name FROM sysobjects WHERE Type='U' and Name = ?
DB.MMS.MOVE.CREATE_TABLE=SELECT * INTO $TARGET_TABLE$ FROM AllShotMMS WHERE 1=2
DB.MMS.MOVE.ALTER_TABLE#1=ALTER TABLE $TARGET_TABLE$ DROP COLUMN MsgID
DB.MMS.MOVE.ALTER_TABLE#2=ALTER TABLE $TARGET_TABLE$ ADD MsgID INT NOT NULL DEFAULT (0)
DB.MMS.MOVE.ALTER_TABLE#3=CREATE UNIQUE INDEX IDX_$TARGET_TABLE$_MsgID on $TARGET_TABLE$(MsgID)

# \ub370\uc774\ud0c0 \uc774\ub3d9
DB.MMS.MOVE.SELECT=SELECT DISTINCT CONVERT(VARCHAR(6),SendDT,112) AS SendDT FROM AllShotMMS WHERE SendResult>1
DB.MMS.MOVE.INSERT=INSERT INTO $TARGET_TABLE$(MsgID, msggroupid, Sender,Receiver,Msg,URL,ReserveDT,TimeoutDT,SendDT,SendResult,Telecom, FILE_PATH1, SUBJECT) SELECT MsgID, msggroupid, Sender,Receiver,Msg,URL,ReserveDT,TimeoutDT,SendDT,SendResult,Telecom, FILE_PATH1, SUBJECT  FROM AllShotMMS WHERE SendResult>1 AND CONVERT(VARCHAR(6),SendDT,112)=?
DB.MMS.MOVE.DELETE=DELETE FROM AllShotMMS WHERE SendResult>1 AND CONVERT(VARCHAR(6),SendDT,112)=?


# MYSQL
#SMS##########################################################
# Table 생성
#DB.MOVE.CHECK_TABLE=SHOW TABLES LIKE ?
#DB.MOVE.CREATE_TABLE=CREATE TABLE $TARGET_TABLE$ LIKE AllShotSMS

# 데이타 이동
#DB.MOVE.SELECT=SELECT DISTINCT DATE_FORMAT(SendDT,'%Y%m') AS SendDT FROM AllShotSMS WHERE SendResult>1
#DB.MOVE.INSERT=INSERT INTO $TARGET_TABLE$ SELECT * FROM AllShotSMS WHERE SendResult>1 AND DATE_FORMAT(SendDT,'%Y%m')=?
#DB.MOVE.DELETE=DELETE FROM AllShotSMS WHERE SendResult>1 AND DATE_FORMAT(SendDT,'%Y%m')=?

#MMS##########################################################
# Table 생성
#DB.MMS.MOVE.CHECK_TABLE=SHOW TABLES LIKE ?
#DB.MMS.MOVE.CREATE_TABLE=CREATE TABLE $TARGET_TABLE$ LIKE AllShotMMS
# 데이타 이동
#DB.MMS.MOVE.SELECT=SELECT DISTINCT DATE_FORMAT(SendDT,'%Y%m') AS SendDT FROM AllShotMMS WHERE SendResult>1
#DB.MMS.MOVE.INSERT=INSERT INTO $TARGET_TABLE$ SELECT * FROM AllShotMMS WHERE SendResult>1 AND DATE_FORMAT(SendDT,'%Y%m')=?
#DB.MMS.MOVE.DELETE=DELETE FROM AllShotMMS WHERE SendResult>1 AND DATE_FORMAT(SendDT,'%Y%m')=?